apiVersion: v1
kind: ConfigMap
metadata:
  name: processador-diagramas-reportingservice-config
  labels:
    app: processador-diagramas-reportingservice
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  ProcessingService__BaseUrl: "http://processador-diagramas-processingservice"
  ProcessingService__TimeoutSeconds: "30"
  Aws__Region: "us-east-1"
  Messaging__Enabled: "true"
  Messaging__PollIntervalSeconds: "3"
  Messaging__WaitTimeSeconds: "10"
  Messaging__MaxNumberOfMessages: "10"
  Queues__AnalysisCompletedQueueName: "upload-orchestrator-analysis-completed"
  Service__Name: "ProcessadorDiagramas.ReportingService"
